apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: small-scale-urban-service-app-argocd
  namespace: argocd
spec:
  # project: small-scale-urban-Service-App
  project: default
  source:
    repoURL: https://github.com/sid14581/Deployment-Small-scale-Urban-Services.git
    targetRevision: HEAD
    path: deploy_files
  destination:
    server: https://kubernetes.default.svc
    namespace: small-scale-urban-service-app-argocd
  
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
  
